django_official/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'))
]

django_official/mysite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('section', views.section, name='section'),
    path('section_post', views.section_post, name='section_post'),
    path('upload', views.upload, name='upload')
]

django_restful/tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from rest_framework import routers
from tutorial.quickstart import views

router = routers.DefaultRouter()
router.register('users', views.UserViewSet)
router.register('groups', views.GroupViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include(router.urls)),
    url('^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework'))
]

app/models.py
from . import db


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Unicode(240), unique=True)
    password = db.Column(db.Unicode(240))
    update_time = db.Column(db.DateTime, index=True)

django_official/mysite/polls/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    uid = models.CharField(max_length=200)


class IdcInfo(models.Model):
    virtual_choice = (
        (0, '否'),
        (1, '是'),
    )
    idc_name = models.CharField(max_length=50, verbose_name=(
        '机房名字'), default=u"", null=True, blank=True)
    is_virtual = models.IntegerField(verbose_name=(
        "是否云主机"), choices=virtual_choice, default=0)

django_restful/tutorial/quickstart/models.py
from django.db import models

# Create your models here.

django_official/mysite/polls/forms.py
from django import forms


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

app/views/user.py
"""User."""
from flask_restaction import abort
from app import model
from app.dependency import db


class User:
    """User.

    $shared:
        userinfo:
            id?int: id
            username?str: username
    """

    def get(self, username):
        """Get user info by username.

        $input:
            username?str: username
        $output: "@userinfo"
        $error:
            404.NotFound: not found
        """
        user = model.User.query.filter_by(username=username).first()
        if user:
            return user
        abort(404, 'not found')

    def post(self, username, password):
        """Post user info.

        $input:
            username?str: username
            password?str: password
        $output: "@userinfo"
        """
        user = model.User.query.filter_by(username=username).first()
        if user:
            abort(400, 'user all ready exist')
        user = model.User(username=username, password=password)
        db.session.add(user)
        db.session.commit()
        return user

django_official/mysite/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .models import IdcInfo
from .forms import UploadFileForm
from .util.upload import handle_uploaded_file
# from django.template import loader

# Create your views here.


def index(request):
    return HttpResponse('hello world')


def section(request):
    is_virtual_list = IdcInfo.objects.all()
    # import pdb
    # pdb.set_trace()
    context = {'is_virtual_list': is_virtual_list}
    context = {'is_virtual_list': [
        choice for choice in IdcInfo.virtual_choice]}
    return render(
        request, "polls/index.html", context)


def section_post(request):
    import pdb
    pdb.set_trace()
    return HttpResponse('hi')


def ajax(request):
    return HttpResponse('hello')


def html(request):
    return render(request, "pools/ajaxttest.html")


@csrf_exempt
def upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            filename = form.cleaned_data.get('title', 'test')
            handle_uploaded_file(filename, request.FILES['file'])
            return HttpResponse('success.')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})
    return HttpResponse('hello')

django_restful/tutorial/quickstart/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from tutorial.quickstart.serializers import UserSerializer, GroupSerializer


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer

app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>vue test</title>
    <script src="/static/js/vue.js"></script>
</head>
<body>
<div>hello world</div>
</script>
</body>
</html>

django_official/mysite/polls/templates/polls/ajaxtest.html
<!DOCTYPE html>
<html>
<head>
    <title>ajax demo</title>
</head>
<body>

<form id="add_form" action="/host/" method="POST">

    {% csrf_token %} 
    主机名：<input type="text" name="hostname" id="h1"><span id="error_msg"></span><br>
    IP：<input type="text" name="IP" id="i1"><br>
    端口：<input type="text" name="port" id="p1"><br>
    <select name="agent" id="s1">业务线
        {% for i in v2 %}
        <option value="{{i.b_id}}">{{i.b__caption}}</option>
        {% endfor %}
    </select>
    <input type="submit" value="提交" >
    <input type="button" value="取消" >
    <a id="a1">ajax提交</a>
 </form>

</body>
</html>

django_official/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <title>demo</title>
</head>
<body>
<form action="/polls/section_post" method="POST">
    {% csrf_token %}
    <select class="form-control m-b" name="is_virtual">
            {% for  is_virtual_i in is_virtual_list %}
                <!-- <option>{{  is_virtual_i.get_is_virtual_display  }}</option> -->
                <option value={{is_virtual_i.0}}>{{is_virtual_i.1}}</option>
            {% endfor %}
        <option value="option2s" name="op">option 2</option>
    </select>
    <input type="submit" name="submit"></input>
</form>

</body>
</html>

django_official/mysite/polls/templates/upload.html
<!DOCTYPE html>
<html>
<head>
	<title>form test</title>
</head>
<body>
	<h1>New post</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">
    	{% csrf_token %}
    	<p>title: {{ form.title }}</p>
    	<p>file: {{ form.file }}</p>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
</body>
</html>